name: Build develop image

on: 
  push:
      branches:
      - 'main'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    name: Build container
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Update Readme.md and description
      uses: meeDamian/sync-readme@v1.0.6
      with:
        user: ${{ secrets.DOCKER_USERNAME }}
        pass: ${{ secrets.DOCKER_PASSWORD }}
        slug: pepaondrugs/ESP32BLE-Sniffer-Stack
        readme: ./README.md
        description: code:https://github.com/PepaonDrugs/ESP32BLE-Sniffer-Stack
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with: 
        context: .
        platforms: linux/amd64,linux/ppc64le,linux/arm64
        file: ./Dockerfile
        push: true
        tags: pepaondrugs/esp32ble-sniffer-stack:latest,pepaondrugs/esp32ble-sniffer-stack:v1.0.0
